name: flame_behaviors_pong_example
description: An example Flame game built with Flame Behaviors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.16.0
  flame_behaviors: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.16.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
