name: flame_behaviors_pong_example
description: An example Flame game built with Flame Behaviors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flame: ^1.2.0
  flame_behaviors: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
