name: flame_behaviors_pong_example

on:
  pull_request:
    paths:
      - ".github/workflows/flame_behaviors_pong_example.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/flame_behaviors_pong_example.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.2
